steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'API_KEY=$_API_KEY'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tiny-closet-api:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tiny-closet-api:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'tiny-closet-api'
      - '--platform=managed'
      - '--image=us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tiny-closet-api:latest'
      - '--region=us-west1'
    entrypoint: gcloud
substitutions:
  _API_KEY: ''
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tiny-closet-api:latest'
